version: 2
updates:
  - package-ecosystem: pip
    directory: "/{{cookiecutter.project_name}}/"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/{{cookiecutter.project_name}}/.github/"
    schedule:
      interval: daily
